# -------------------------------------------------------
# -- The backwards compatiable docker-compose definition
# -- ...in case you don't have docker version 1.10 or later.
#
# # -- Make a spot for it
# sudo mkdir -p /opt/bin
# # -- Download it
# sudo bash -c 'curl -L https://github.com/docker/compose/releases/download/1.6.2/run.sh > /opt/bin/docker-compose'
# # -- make it executable
# sudo chmod +x /opt/bin/docker-compose
# # -- this will pull it.
# docker-compose -v
#
# # -- clone it
# git clone https://github.com/sipcapture/homer-docker.git
# cd homer-docker

# # -- build it!
# docker-compose --file docker-compose-v1.yml build
# # -- That will fail, it's OK, have to do a manual step
# docker tag homerdocker_webapp qxip/homer-webapp
# # -- Build again
# docker-compose --file docker-compose-v1.yml build
# # -- Pull what's left.
# docker-compose --file docker-compose-v1.yml build

# --------------------------------------------- MySQL container.
mysql:
  container_name: mysql
  image: mysql:5.6
  volumes:
    - ./mysql/run.sh:/run.sh
    - /var/data-homer/homer-semaphore/:/homer-semaphore/
    - /etc/localtime:/etc/localtime
    - /var/data-homer/db/:/var/lib/mysql
  entrypoint:
    - /run.sh
  env_file:
    - ./homer.env
# --------------------------------------------- Web app container
webapp:
  container_name: homer-webapp
  build: ./webapp/.
  ports:
    - "80:80"
  volumes:
    - /homer-api/
    - /var/data-homer/homer-semaphore/:/homer-semaphore/
  links:
    - "mysql:mysql"
  env_file:
    - ./homer.env
# --------------------------------------------- cron container
cron:
  container_name: homer-cron
  build: ./cron/.
  volumes:
    - /var/data-homer/homer-semaphore/:/homer-semaphore/
  links:
    - "mysql:mysql"
  env_file:
    - ./homer.env
# --------------------------------------------- Kamailio container
kamailio:
  container_name: homer-kamailio
  build: ./kamailio/.
  ports:
    - "9060:9060/udp"
  links:
    - "mysql:mysql"
  volumes:
    - /var/data-homer/homer-semaphore/:/homer-semaphore/
  # entrypoint:
  #   - /bin/bash
  # command:
  #   >
  #   -c 'while true; do sleep 60; done;'
  env_file:
    - ./homer.env      
# --------------------------------------------- Data bootstrapping container
bootstrap:
  container_name: bootstrap-mysql
  image: mysql:5.6
  links:
    - "mysql:mysql"
  volumes_from:
    - webapp
  volumes:
    - /var/data-homer/homer-semaphore/:/homer-semaphore/
    - ./bootstrap-data/bootstrap.sh:/bootstrap.sh
  # entrypoint:
  #   - /bin/bash
  # command:
  #   >
  #   -c 'while true; do sleep 60; done;'
  entrypoint:
    - /bootstrap.sh
  env_file:
    - ./homer.env      
