apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: cron
  name: cron
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: cron
status:
  loadBalancer: {}
