apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: mysql
    spec:
      containers:
      - command:
        - /run.sh
        env:
        - name: TZ
          value: '"Etc/UTC"'
        - name: DB_USER
          value: homer_user
        - name: DB_PASS
          value: homer_password
        - name: USE_REMOTE_MYSQL
          value: "false"
        - name: DB_HOST
          value: mysql
        - name: DB_PORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        - name: KAMAILIO_HEP_PORT
          value: "9060"
        image: mysql:5.6
        name: mysql
        resources: {}
        volumeMounts:
        - mountPath: /run.sh
          name: mysql-claim0
        - mountPath: /homer-semaphore/
          name: homer-data-semaphore
        - mountPath: /var/lib/mysql
          name: homer-data-mysql
      restartPolicy: Always
      volumes:
      - name: mysql-claim0
        persistentVolumeClaim:
          claimName: mysql-claim0
      - name: homer-data-semaphore
        persistentVolumeClaim:
          claimName: homer-data-semaphore
      - name: homer-data-mysql
        persistentVolumeClaim:
          claimName: homer-data-mysql
status: {}
