apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: webapp
  name: webapp
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    service: webapp
status:
  loadBalancer: {}
