apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: webapp
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: webapp
    spec:
      containers:
      - env:
        - name: TZ
          value: '"Etc/UTC"'
        - name: DB_USER
          value: homer_user
        - name: DB_PASS
          value: homer_password
        - name: USE_REMOTE_MYSQL
          value: "false"
        - name: DB_HOST
          value: mysql
        - name: DB_PORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        - name: KAMAILIO_HEP_PORT
          value: "9060"
        image: sipcapture/homer-webapp
        name: homer-webapp
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /homer-api/
          name: webapp-claim0
        - mountPath: /homer-semaphore/
          name: homer-data-semaphore
        - mountPath: /var/www/html/store/dashboard/
          name: homer-data-dashboard
      restartPolicy: Always
      volumes:
      - name: webapp-claim0
        persistentVolumeClaim:
          claimName: webapp-claim0
      - name: homer-data-semaphore
        persistentVolumeClaim:
          claimName: homer-data-semaphore
      - name: homer-data-dashboard
        persistentVolumeClaim:
          claimName: homer-data-dashboard
status: {}
