apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: homer-data-dashboard
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: homer-data-mysql
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 250Mi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: homer-data-semaphore
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Mi
status: {}
---