apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: homer-data-dashboard
  # This storage class is a work around for now...
  # see: https://github.com/kubernetes/kubernetes/issues/43929
spec:
  storageClassName: storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: homer-data-mysql
spec:
  storageClassName: storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: homer-data-semaphore
spec:
  storageClassName: storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
status: {}
---