apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: bootstrap
  name: bootstrap
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: bootstrap
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: cron
  name: cron
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: cron
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: kamailio
  name: kamailio
spec:
  ports:
  - name: "9060"
    port: 9060
    protocol: UDP
    targetPort: 9060
  selector:
    service: kamailio
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: mysql
  name: mysql
spec:
  clusterIP: None
  ports:
  - name: "3306"
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    service: mysql
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: webapp
  name: webapp
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    service: webapp
status:
  loadBalancer: {}
---
